### ISSUE TITLE
Can't save

### ISSUE THREAD

**Issue by AcarBurak** [zrax/qtextpad#1]
Brilliant idea and necessary program; wish you didn't abandon it.

Can't save a document in any way, Save, Save As…

On another note, lots of warning about unused or deprecated things during installation (on Arch Linux).

**Comment by AcarBurak** [comment]
Themes aren't applied either, though syntax highlighting is OK.

By the way, unless I comment out the https://github.com/zrax/qtextpad/blob/a87164eee00babc0509acd5afde0a81a4ba5648a/syntaxtextedit.cpp#L144 I get LOTS of empty lines at the end of the documents. But don't get me wrong, I'm just a simple user, not a coder.

**Comment by zrax** [comment]
It's true, I never implemented saving... :(.  It's probably the most-needed feature if I get back to working on this again.

As for the scrollPastEndOfFile, those aren't empty lines, but rather a feature that lets you scroll until the last (real) line of the file is at the top of the window rather than the bottom.  It should be an option, but for now I just hard-code it due to the odd behavior mentioned in the comment.
