### ISSUE TITLE
Shortcuts…

### ISSUE THREAD

**Issue by AcarBurak** [zrax/qtextpad#9]
There are no key bindings for "Save As…" and "Replace…" since (I gather) these two are the only ones [without common bindings for both KDE and Gnome](https://doc.qt.io/qt-5/qkeysequence.html) and I'm neither in KDE nor in Gnome.

Though, for instance, I could figure out to replace your https://github.com/zrax/qtextpad/blob/1d3dd5fadc8650b0ef541d0a58c58c5d6eb1113b/qtextpadwindow.cpp#L203

with `Qt::CTRL | Qt::Key_R`, you might consider doing similar yourself for other non-KDE or non-Gnome users.

On another note, some hidden Qt shortcuts work beautifully like `Ctrl+Backspace` and `Ctrl+K` etc., but not `Ctrl+U` to delet a line.

Thanks for the "fancy copy/cut" convenience.

**Comment by zrax** [comment]
I'm hesitant to deviate from QKeySequence's standard shortcuts without replacing its use everywhere...  I haven't decided what to do about that yet, but I'll probably end up looking into Qt's sources at some point to see how bad the shortcut situation really is.


> [...] but not Ctrl+U to delete a line.

I've never seen Ctrl+U for deleting a line...  What editor(s) are you seeing this in?

For reference, I looked at:
* kate: Ctrl+U capitalizes the current letter or selection; Ctrl+K deletes line
* gedit: Ctrl+U capitalizes the current letter or selection; Ctrl+D deletes line
* Notepad2: Ctrl+U lowercases the current selection; Ctrl+Shift+D deletes line
* vscode: Ctrl+U is "soft undo"; Ctrl+Shift+K deletes line
* clion: Ctrl+U is "goto supermothod"; Ctrl+Y deletes line
* qtcreator: Ctrl+U selects the current bracket range; No delete line that I could find

As you can see, not a whole lot of consistency here...  I'll probably just pick one, but which one might depend on whether I refactor all the shortcuts or not.

**Comment by AcarBurak** [comment]
QKeySequence is OK; it's easy for me to replace it with `sed` before compilation; it's automatic with my PKGBUILD.

As for the Ctrl+U binding, sorry, I've seen it in the above link: https://doc.qt.io/qt-5/qkeysequence.html

By the way, have you seen my https://github.com/zrax/qtextpad/issues/8#issuecomment-525815747?

**Comment by AcarBurak** [comment]
And seemingly Ctrl+U is used for underline as well!

**Comment by zrax** [comment]
After digging into the sources a bit, it looks like Qt actually does the right thing, but only when the desktop correctly reports what it is through `XDG_CURRENT_DESKTOP` (and of course only for DEs that Qt knows).  As an example, when running on xfce started standalone over VNC (which is a common use case of mine), xfce-session does **not** correctly set `XDG_CURRENT_DESKTOP`, meaning that the platform support plugin treats the app as "Generic Unix" rather than "XFCE".  Setting `XDG_CURRENT_DESKTOP=xfce`(or the equivalent for your DE) causes the shortcuts to be mapped correctly, as well as affecting other desktop-specific settings such as toolbar icons.

**Comment by AcarBurak** [comment]
Yes, I know, but setting XDG_CURRENT_DESKTOP to something has some other adverse consequences if I recall correctly, but I don't remember what they were. No big deal; `sed` is my friend.
